### ISSUE TITLE
How to open the project?

### ISSUE THREAD

**Issue by leoom** [bq/horus#11]
How to open the entire project? Is it possible?
Is there any documentation of the codes?

**Comment by Jesus89** [comment]
Hi,

To develop the project, Ubuntu and Sublime Text are recommended.

You need to install all dependencies described in README.md and execute "python src/horus.py".
If you want to execute the project from Windows you need to use PortablePython included in .exe file.

**Comment by leoom** [comment]
Gracias.

Estoy haciendo un proyecto en la escuela que se relaciona con el escáner 3D pero no sé por dónde empezar. Pero voy a empezar a tratar de entender Horus.

**Comment by Jesus89** [comment]
Genial! :D
