### ISSUE TITLE
French

### ISSUE THREAD

**Issue by deusyss** [bq/horus#12]
Hi, here is the new french.po file (i had forgot some lines in po file). Please change ext from png to po.
![fr](https://cloud.githubusercontent.com/assets/5519444/6562634/2c864204-c69b-11e4-823f-3d13d8a8cd98.png)

**Comment by Jesus89** [comment]
Can you make a pull request into "french-tr" branch?
Thanks!

**Comment by deusyss** [comment]
Hi. Pull request created
