### ISSUE TITLE
A question about launching horus

### ISSUE THREAD

**Issue by a312514554** [bq/horus#14]
Errorlog in Ubuntu in the terminal：
File "/home/dc/horus/src/horus/gui/workbench/calibration/pages.py", line 481, in initialize
    fig = Figure(facecolor=(0.7490196,0.7490196,0.7490196,1), tight_layout=True)
TypeError: __init__() got an unexpected keyword argument 'tight_layout'

Is the problem located in the function “Figure”？Or any package I forget to import？Thanks！

**Comment by Jesus89** [comment]
Hi!
Are you using Windows or Linux? Have you installed all the dependencies?

**Comment by a312514554** [comment]
yeah,I'm using ubuntu(linux),And had installed all the depedencies follow the step you mentioned at https://github.com/bq/horus

**Comment by Jesus89** [comment]
Which version of Ubuntu? Probably you need to update your matplotlib up to 1.3.1
Please, check version using:
python
import matplotlib
print matplotlib.__version__

**Comment by a312514554** [comment]
Ubuntu's version is 12.04, is that OK?According to your guide:

**Comment by Jesus89** [comment]
Ok. Horus works from Ubuntu 14.04 because of the dependencies. I encourage you to install this new version of Ubuntu.
Regards!

**Comment by a312514554** [comment]
I have updated my OS to 14.04. Another question is what the type of the Red line laser(5V) is in your Ciclop-BOM.pdf. How about the general type?

**Comment by Jesus89** [comment]
Hi, our laser is a Class 1 5V red line laser with 60º of aperture "bq-made". You can use also another line lasers. There are some people in the community using them.

For future questions or discussions about Horus, please use our Google Group: https://groups.google.com/forum/?hl=en#!forum/ciclop-3d-scanner instead of a GitHub issue.

Regards!
