### ISSUE TITLE
Point cloud data collected by CICLOP

### ISSUE THREAD

**Issue by a312514554** [bq/horus#15]
I have made a CICLOP by myself, and I used Horus to reconstruct the point cloud datas by the two red line lasers and camera. But I found a question about the point cloud datas. Here are my model and my point cloud data pictures.

**Comment by Obijuan** [comment]
You've forgotten to upload the pictures / point clouds

**Comment by a312514554** [comment]
![Uploading QQ截图20150329171544.png . . .]()

**Comment by a312514554** [comment]
Sorry, the netspeed is so bad. I will change my net to upload the pictures!

**Comment by a312514554** [comment]
![qq 20150329171544](https://cloud.githubusercontent.com/assets/8042696/6884871/d2cd50fc-d637-11e4-9113-1f3b55d6cb05.png)
From the picture, it is easy to find the real model 'Baymax' was scanned in Horus by CICLOP. But the point cloud datas in Horus has four arms, it seems like the point cloud datas collected by the left red line laser and the point cloud datas collected by the right red line laser have no registration, which leaded to there were two baymax in the Horus. If there are registration methods in Horus, will the result be better? Or are there some details have been ignored?

**Comment by a312514554** [comment]
Sorry for the late reply, I have changed my net to upload the picture.

From the picture, it is easy to find the real model 'Baymax' was scanned in Horus by CICLOP. But the point cloud datas in Horus has four arms, it seems like the point cloud datas collected by the left red line laser and the point cloud datas collected by the right red line laser have no registration, which leaded to there were two baymax in the Horus. If there are registration methods in Horus, will the result be better? Or are there some details have been ignored?
![qq 20150329171544](https://cloud.githubusercontent.com/assets/8042696/6889748/a26a8a54-d6cf-11e4-8cb6-08f112fb98c6.png)

**Comment by Jesus89** [comment]
Hi!

We will implement registration soon, but it is not necesary yet. The problem here is that calibration parameters are not correct (camera intrinsics, pattern distance, pattern square...) We will upload User's Manual soon to explain how to calibrate correctly with Horus.

For future questions or discussions about Horus, please use our Google Group: https://groups.google.com/forum/?hl=en#!forum/ciclop-3d-scanner instead a GitHub issue.

Regards!
