### ISSUE TITLE
Connection error!

### ISSUE THREAD

**Issue by a312514554** [bq/horus#16]
I have use the Horus in my classmate's computer, it works successfully. But when I use the Horus, connecting the board and camera with USB, opening the Horus, error comes out. It shows "The board is not connected. Please connect your board and select a valid Serial Name". I set the baudrate 115200. Could you help me?

**Comment by Jesus89** [comment]
Are you using Windows or Linux? Have you installed the drivers? What is the Serial Name of your board? Have you tried connecting your board with Putty or Cutecom?
Please, for future issues write our Group: https://groups.google.com/forum/?hl=en#!forum/ciclop-3d-scanner.
Thank you!

**Comment by jorgerobles** [comment]
Also, I've encountered on not genuine Ciclop's boards (custom builds) that trying to connect with motor powered pollutes the serial connection information transfer. Try to connect first without motor power, then power it on.
