### ISSUE TITLE
[MAC] Connection

### ISSUE THREAD

**Issue by Jesus89** [bq/horus#26]
Combos in Preferences
Burn firmware
UVC crashes with wrong id
Reconnect Camera and Board

**Comment by jorgerobles** [comment]
I've experienced that the reconnect is fired when the shield is on. It garbles the handshake message.

**Comment by Jesus89** [comment]
I have observed that only board reconnect is possible when cable is unplugged and plugged in.
To reconnect the camera Horus must be restarted, by now.

**Comment by Jesus89** [comment]
Combos in Preferences: 02e2b52b2a68d884fb2c71e646283cd3afebc9f3
UVC crashes with wrong id: 7f11ab090134cec2bd9f3173a1103a90222c7b04

There are problems with pyserial, uvc and USB reconnection.

**Comment by Jesus89** [comment]
Done!

Burn firmware: 883bccabbc42a14ff9323150e45c708a3886feb1
Reconnect Board: 3cea78c139822c8a3a7b5bd851189b77be0789af
Reconnect Camera: c2ef3e03ee56e13de72fbcaf9562818b7f1d425c

It is needed to install FTDI drivers for mac.

**Comment by jorgerobles** [comment]
Congratulations! You're the F*****n Boss.
