### ISSUE TITLE
Improvement about Horus.

### ISSUE THREAD

**Issue by a312514554** [bq/horus#29]
I have some questions about the Horus, I have assemble a CICLOP scanner by myself. It works successfully,but I found many shortcomings about it. The data collected by CICLOP is point cloud data, but if I want to use it on my own DIY 3D orinter, I must edit the ply file in Geomagic software, I think it is incovenient for a user to do like this. I think improvement should be made on how to convert the ply file to STL mode rapidlly, or any details I have ignored?

**Comment by Jesus89** [comment]
Hi!,
As we commented in the presentation post: http://diwo.bq.com/en/horus-released/ we want to include a complete point cloud post-processing interface in Horus, also to generate the mesth (STL). This is a future feature, but thank you for the suggestion.
Regards!
