### ISSUE TITLE
Hello, question about the horus!

### ISSUE THREAD

**Issue by a312514554** [bq/horus#3]
Hello, I am interested in your horus, I have downloaded horus-develop software. When I opened the horus.py by python, error came out! My OS is WIN7.
![qq 20150209155700](https://cloud.githubusercontent.com/assets/8042696/6102894/6bff0918-b078-11e4-930f-8a2a4e92cfae.png) it shows DLL load failed and it is not a efficient WIN32 application.
I have installed python-wxgtk2.8, python-opengl, python-serial, python-numpy, python-pyglet, python-matplotlib, python-scipy and python-opencv. What's wrong with it ?

**Comment by a312514554** [comment]
Can you make it more convenient to use the software or I missed anything with it ?

**Comment by Jesus89** [comment]
Hi!

It seems that you have a problem in Python installation and some of the modules: http://stackoverflow.com/questions/14629818/importerror-dll-load-failed-1-is-not-a-valid-win32-application, https://www.youtube.com/watch?v=fGuHMVAruAE

Horus has been developed in Linux (Ubuntu), but we have an .exe file to install it in windows. You can find this executable file here: http://diwo.bq.com/en/horus-released/. It installs a portable python version and all dependencies. It also contains the sources (extracted into program files).

I hope any of these solutions work for you.

Let me know if you have success.

Regards!

**Comment by a312514554** [comment]
Thanks, I still have some problems about the Horus, and I want to DIY a the device, do you have any information about install all the device(include software. hardware. mechanical structure and circuits)?

**Comment by Jesus89** [comment]
Hi. We will publish this information (assembly manual, software user's manual, videos) on March.
