### ISSUE TITLE
OsX 10.10 camera issues when Logitech camera + MacBookPro retina camera

### ISSUE THREAD

**Issue by sdelrio** [bq/horus#30]
A friend called me this weekend to see if we could make the horus work for his ciclops scanner on MacBook Pro (Retina, 13" late 2013) (OsX 10.10.3 Yosemite).

After resolving some python dependencies and starting the program, we found this error when clicking on connect after starting the wizard:
```
>> Connecting camera 0
Jun  6 22:33:59 MacBook-Pro-de-sdelrio.local se.dm9.uvcc[979] <Error>: uvccGetCamWithQTUniqueID: supplied string is not an QTKit unique ID
[...]
AssertionError: UVCC could not open camera based on uId DJH4273WLVJF6VTD3
```

Horus seems not trying other cameras (the Logitech USB C270 was connected on USB), because on the console only can find "connecting camera 0".

On system information we could find that this ID is the camera from the notebook, not the Logitech USB. And it seems that it doesn't look for more after it.

```
FaceTime HD Camera:

  N.º de modelo:	Apple Camera VendorID_0x106B ProductID_0x1570
  Identificador único:	DJH4273WLVJF6VTD3

Cámara USB #2:

  N.º de modelo:	UVC Camera VendorID_1133 ProductID_2085
  Identificador único:	0x14200000046d0825
```

After searching on source code, it seems that there is a list containing the cameras.

`src/horus/engine/camera.py` line 106:
```python
       if sys.isDarwin():
            for device in uvc.mac.Camera_List():
                 if device.src_id == self.cameraId:
                     self.controls = uvc.mac.Controls(device.uId)
```

And looking for the  class Camera_List I found it looks for `QTMediaTypeVideo`:

`src/horus/engine/uvc/mac/__init__.py` line 142:
```python
class Camera_List(list):
    """docstring for uvcc_control"""

    def __init__(self):
        if getattr(sys, 'frozen', False):
            #explicit import needed when frozen
            import QTKit

        from QTKit import QTCaptureDevice,QTMediaTypeVideo
        qt_cameras =  QTCaptureDevice.inputDevicesWithMediaType_(QTMediaTypeVideo)
        for src_id,q in enumerate(qt_cameras):
            uId =  q.uniqueID()
            name = q.localizedDisplayName().encode('utf-8')
            self.append(Cam(name,uId,src_id))
```

We found is that if we start FaceTime (or another program that uses webcam) and change the default integrated macbook camera (FaceTime camera) for the one on USB, it seems to initialize the device as Camera and probably the system changes the time of the device to `QTMediaTypeVideo` and then Horus could **see** it. But still, it seems that only tries to load the first device found.

My friend has an older MacbookPro without camera (Mountain Lion 10.8.4). If we make this steps we made hours to show video with logitech C270:

1. start an application that uses webcam
2. select the Logitech C270, and check the pass uses it
3. close webcam app and start Horus.

- Horus version used  0.1.1.1 (git clone used this weekend)

I could only stay 2 hours testing at my friend's home, so I didn't have time to set up some traces and look for more information. I think he already emailed you and wrote on the list, but if I can help just let me know.

**Comment by Jesus89** [comment]
Hi! We are using Horus on Mac, but it's still on development.
Try simply to install QTKit: https://pypi.python.org/pypi/pyobjc-framework-QTKit
We hope to close Mac issues during this week.
Regards!

**Comment by Jesus89** [comment]
Hi! I have solved most mac issues here: https://github.com/bq/horus/tree/release/0.1.2.
Regards!

**Comment by sdelrio** [comment]
Thank you very much Jesus89. I've told to my friend (because I don't have the ciclops) and saw the USB FTDI .dmg.

**Comment by sdelrio** [comment]
Hello Jesus89, my friend confirmed that v 0.1.2 on iMac 5k works (that also comes with camera over the screen). We could not test on MacBookPro Retina this week. But I hope we can do long next one.

**Comment by sdelrio** [comment]
Tested on MBP Retina. Closing issue.

**Comment by Jesus89** [comment]
Great!  :D

**Comment by neshmi** [comment]
This also works for me on a MBP 15" Retina. With versions pre-0.1.2 I didn't have the option to set preferences for my camera, only 0 showed up. With 0.1.2, I could then select 1 and then everything worked.
