### ISSUE TITLE
.dmg generator builds empty .dmg

### ISSUE THREAD

**Issue by ariuskooo** [bq/horus#31]
While building .dmg with provided builder i've got this error: execution error: Finder got an error: Can’t set item "Horus.app" of disk "Horus Installer" to {180, 280}. (-10006)
It still create .dmg but its empty

**Comment by Jesus89** [comment]
Hi! Here is the documentation: https://github.com/bq/horus/blob/release/0.1.2/doc/development/darwin.md. Unmount all "Horus Installer" disks if you have it.
