### ISSUE TITLE
Mac OS installer

### ISSUE THREAD

**Issue by Jesus89** [bq/horus#4]

**Comment by bolsoncerrado** [comment]
+1 a un instalador Mac! :D

**Comment by litris** [comment]
Estaría de lujo para Mac ;-)

**Comment by litris** [comment]
+1

**Comment by ramengo** [comment]
i had buy the scanner, but i have OS X S.O, what i can do for use the scanner?
i have a  problem on parallels with windows 7 for the uncorrect id camera!
In how may times the native OS X software born?
Thanks

**Comment by Jesus89** [comment]
Added dmg gen: ff3b26ee217127b2a03fc6db0b2a989ffe2cf0d6

Execute "bash package.sh darwin" to generate it.

**Comment by ariuskooo** [comment]
I've got this error: execution error: Finder got an error: Can’t set item "Horus.app" of disk "Horus Installer" to {180, 280}. (-10006)
It still create .dmg but its empty

**Comment by D2-Nemo** [comment]
Seriously, why not simply build a DMG for all mac users? This would be way simpler !

**Comment by D2-Nemo** [comment]
I happend to build the dmg, but have the same error as ariuskooo
