### ISSUE TITLE
Error in camera connection

### ISSUE THREAD

**Issue by javivi001** [bq/horus#45]
When horus was closed with the camera expousure at 512., the next time you open horus and connect to the camera, horus connect but can't manage the camra and shows the reconnect the camera error. At least it happens on mac.

Thruobleshoting: reset profile, close horus and open again. 

Regards. 

Javi

**Comment by Jesus89** [comment]
Hi, an exposure value of 512 means very very slow image capture. Now only 128 max is allowed.
