### ISSUE TITLE
[MAC] Camera issues

### ISSUE THREAD

**Issue by jorgerobles** [bq/horus#6]
Hi:
After a few tests, Horus rejects the camera device as can not read Exposure values. 
Maybe further read of http://phoboslab.org/log/2009/07/uvc-camera-control-for-mac-os-x could fix it.

**Comment by Jesus89** [comment]
We had the same problem in Linux with UVC cameras. We made some hacks in OpenCV source code to solve this issue with V4L driver: https://github.com/bq/opencv.

Thank you for the info! :)

**Comment by jorgerobles** [comment]
the opencv running on my system is the bq one :-/
if you have any directives to add on cmake please tell me.

El 13/02/2015, a las 16:06, "Jesús Arroyo Torrens" <notifications@github.com>
escribió:

We had the same problem in Linux with UVC cameras. We made some hacks in
OpenCV source code to solve this issue with V4L driver:
https://github.com/bq/opencv.

Thank you for the info! :)

—
Reply to this email directly or view it on GitHub
<https://github.com/bq/horus/issues/6#issuecomment-74267018>.

**Comment by jorgerobles** [comment]
I've check the OpenCV on cmake and shows missing v4l package. Unfortunately I didn't found a way to install those libraries on OSX.

**Comment by jorgerobles** [comment]
Update2: I've got UVC capture running on my build. Check my fork for tests and code.

**Comment by Jesus89** [comment]
Hi! Good Job :)

We will test it. Do you think there is a way to include those hacks on OpenCV libraries? I think it would be a great solution.

**Comment by jorgerobles** [comment]
I think is possible, I was thinking the same, (despite check author licensing, etc.) the library is surprisingly tiny, but I'm no good at C Language.

**Comment by jorgerobles** [comment]
Hi again, what's the reasonale of the setExposure formula for checkCamera?
What values are expected? I've got to map them from the values return with UVCC (and the other camera levels too...)

**Comment by Jesus89** [comment]
Hi!

CheckCamera is a function to differentiate Laptop camera from Logitech C270. Simply I set some value of Exposure (ex. 2) and get the Exposure and check if it is the same value, but maybe there would be another ways to do it.

There are differences in the camera drivers when implementing the exposure.

The driver in linux is v4l2 (http://www.linuxtv.org/downloads/legacy/video4linux/API/V4L2_API/spec-single/v4l2.html#camera-controls). The value of exposure is measured in units of 100 us . Generally t goes from 0.1 ms to 1000 ms.

On Windows , DirectShow uses the exposure value considering the formula e = -log2 (t ) . And the range and negative discrete values ​​are : 0 , -1, -2 , ... , -9 , which correspond to discrete values ​​of t, 1, 2, 4, ... 512 ms.

To unify the range of exposure in the implementation, interval (1, 512) ms is selected. The step is 1 ms linux and windows 2 ** (1, ..., 9 )

I don't know how this works on MacOS.

**Comment by nallath** [comment]
In some cases the exposure is camera specific.

**Comment by Jesus89** [comment]
Bugs:

* Wrong exposure scale
* Frame Rate fails
* Resolution fails

**Comment by Jesus89** [comment]
Exposure scale bugfixed: 863d5767884b5ca9d26349533a5dd7bf1e2e8b4a

For frame rate and resolution UVC_capture uses directly OpenCV. Frame rate doesn't work and resolution works but gets frozen.

Checking OpenCV modules for Mac is needed.

**Comment by Jesus89** [comment]
Disabled Frame Rate and Resolution in Mac: 7ecf128769c6e72a54b0dae9d38536edd1096144

New issue for OpenCV fps and resolution in Mac: https://github.com/bq/horus/issues/27
