### ISSUE TITLE
About purchasing the CICLOP machine

### ISSUE THREAD

**Issue by a312514554** [bq/horus#9]
Dear Jesus,
I am a student in Wuhan University of Technology, China, my major is reverse engineering, after knowing the CICLOP in Github, I was fascinated by this machine. Because I am interested in the software, so I cannot assemble the machine and the circuits. So I want to buy a complete machine so that I can concentration on the arithmetic on the reverse engineering. I want to buy the complete machine from you. Could you help me? If you will, how much will it cost? I am looking forward to your reply!
                                                                                                                                                      Liu Jiayi
                                                                                                                                                 02/03/2015

**Comment by Jesus89** [comment]
Hi! We will sell the full Ciclop Kit on March. For more information contact with http://www.bq.com/gb/contact.html. Thanks!
